---
- name: Install Active Directory integration packages
  ansible.builtin.dnf:
    name:
      - realmd
      - sssd
      - adcli
      - oddjob
      - oddjob-mkhomedir
      - krb5-workstation
      - samba-common-tools
    state: present

- name: Join Linux server to Active Directory
  ansible.builtin.shell: |
    echo "{{ vault_ad_admin_password }}" | realm join casestudy.local -U Administrator
  args:
    creates: /etc/sssd/sssd.conf
  no_log: true

- name: Grant sudo access to linux-sudoers AD group
  ansible.builtin.copy:
    dest: /etc/sudoers.d/linux-sudoers
    content: |
      %linux-sudoers@casestudy.local ALL=(ALL) ALL
    owner: root
    group: root
    mode: '0440'
    validate: /usr/sbin/visudo -cf %s
